local testList = {}
Append(testList, "aaa")
Append(testList, "bbb")
Append(testList, 123)
Append(testList, 23)
Append(testList, "45")
Append(testList, "345")
Append(testList, "aaa9")
Append(testList, "aaa80")
Append(testList, "aaa9bbb")
Append(testList, "aaa9aaa")
Append(testList, "a1a2a11")
Append(testList, "a1a2a3")

local expected = {}
Append(expected, 23)
Append(expected, "45")
Append(expected, 123)
Append(expected, "345")
Append(expected, "a1a2a3")
Append(expected, "a1a2a11")
Append(expected, "aaa")
Append(expected, "aaa9")
Append(expected, "aaa9aaa")
Append(expected, "aaa9bbb")
Append(expected, "aaa80")
Append(expected, "bbb")

table.sort(testList, CompareAlphanumerical)

Assert("CompareAlphaumerical", expected, testList)